package command

import (
	_ "net/http/pprof"

	_ "github.com/bookstairs/bookworm/filer/arangodb"
	_ "github.com/bookstairs/bookworm/filer/cassandra"
	_ "github.com/bookstairs/bookworm/filer/elastic/v7"
	_ "github.com/bookstairs/bookworm/filer/etcd"
	_ "github.com/bookstairs/bookworm/filer/hbase"
	_ "github.com/bookstairs/bookworm/filer/leveldb"
	_ "github.com/bookstairs/bookworm/filer/leveldb2"
	_ "github.com/bookstairs/bookworm/filer/leveldb3"
	_ "github.com/bookstairs/bookworm/filer/mongodb"
	_ "github.com/bookstairs/bookworm/filer/mysql"
	_ "github.com/bookstairs/bookworm/filer/mysql2"
	_ "github.com/bookstairs/bookworm/filer/postgres"
	_ "github.com/bookstairs/bookworm/filer/postgres2"
	_ "github.com/bookstairs/bookworm/filer/redis"
	_ "github.com/bookstairs/bookworm/filer/redis2"
	_ "github.com/bookstairs/bookworm/filer/redis3"
	_ "github.com/bookstairs/bookworm/filer/sqlite"
	_ "github.com/bookstairs/bookworm/filer/tikv"
	_ "github.com/bookstairs/bookworm/filer/ydb"
	_ "github.com/bookstairs/bookworm/remote_storage/azure"
	_ "github.com/bookstairs/bookworm/remote_storage/gcs"
	_ "github.com/bookstairs/bookworm/remote_storage/s3"
	_ "github.com/bookstairs/bookworm/replication/sink/azuresink"
	_ "github.com/bookstairs/bookworm/replication/sink/b2sink"
	_ "github.com/bookstairs/bookworm/replication/sink/filersink"
	_ "github.com/bookstairs/bookworm/replication/sink/gcssink"
	_ "github.com/bookstairs/bookworm/replication/sink/localsink"
	_ "github.com/bookstairs/bookworm/replication/sink/s3sink"
)
